import { repoRoot, repoFileURL } from "./helpers.js";

/**
 * @typedef {"adders" | "two-modules" | "html-inline" | "html-external"} Examples
 * @type {{ [key in Examples]:  import('../').ICEntry }} */
export const expectedICSLogs = {
	adders: {
		type: "ics",
		id: "327",
		functionName: "addAny",
		file: repoRoot("examples/simple/adders.js"),
		line: 93,
		column: 27,
		severity: 3,
		updates: [
			{
				type: "LoadIC",
				oldState: "premonomorphic",
				newState: "monomorphic",
				key: "x",
				map: 1629778848081,
				optimizationState: "optimizable",
				severity: 1,
				modifier: "",
				slowReason: "",
			},
			{
				type: "LoadIC",
				oldState: "monomorphic",
				newState: "polymorphic",
				key: "x",
				map: 1629778836321,
				optimizationState: "optimizable",
				severity: 2,
				modifier: "",
				slowReason: "",
			},
			{
				type: "LoadIC",
				oldState: "polymorphic",
				newState: "polymorphic",
				key: "x",
				map: 1629778834561,
				optimizationState: "optimizable",
				severity: 2,
				modifier: "",
				slowReason: "",
			},
			{
				type: "LoadIC",
				oldState: "polymorphic",
				newState: "polymorphic",
				key: "x",
				map: 1629778832961,
				optimizationState: "optimizable",
				severity: 2,
				modifier: "",
				slowReason: "",
			},
			{
				type: "LoadIC",
				oldState: "polymorphic",
				newState: "megamorphic",
				key: "x",
				map: 1629778833441,
				optimizationState: "optimizable",
				severity: 3,
				modifier: "",
				slowReason: "",
			},
			{
				type: "LoadIC",
				oldState: "megamorphic",
				newState: "megamorphic",
				key: "x",
				map: 1629778834001,
				optimizationState: "optimized",
				severity: 3,
				modifier: "",
				slowReason: "",
			},
			{
				type: "LoadIC",
				oldState: "megamorphic",
				newState: "megamorphic",
				key: "x",
				map: 1629778832321,
				optimizationState: "optimized",
				severity: 3,
				modifier: "",
				slowReason: "",
			},
			{
				type: "LoadIC",
				oldState: "megamorphic",
				newState: "megamorphic",
				key: "x",
				map: 1629778828561,
				optimizationState: "optimized",
				severity: 3,
				modifier: "",
				slowReason: "",
			},
		],
	},

	"two-modules": {
		type: "ics",
		id: "333",
		functionName: "addAny",
		file: repoRoot("examples/two-modules/adders.js"),
		line: 38,
		column: 27,
		severity: 3,
		updates: [
			{
				type: "LoadIC",
				oldState: "premonomorphic",
				newState: "monomorphic",
				key: "x",
				map: 61357696723281,
				optimizationState: "optimizable",
				severity: 1,
				modifier: "",
				slowReason: "",
			},
			{
				type: "LoadIC",
				oldState: "monomorphic",
				newState: "polymorphic",
				key: "x",
				map: 61357696711521,
				optimizationState: "optimizable",
				severity: 2,
				modifier: "",
				slowReason: "",
			},
			{
				type: "LoadIC",
				oldState: "polymorphic",
				newState: "polymorphic",
				key: "x",
				map: 61357696709761,
				optimizationState: "optimizable",
				severity: 2,
				modifier: "",
				slowReason: "",
			},
			{
				type: "LoadIC",
				oldState: "polymorphic",
				newState: "polymorphic",
				key: "x",
				map: 61357696708161,
				optimizationState: "optimizable",
				severity: 2,
				modifier: "",
				slowReason: "",
			},
			{
				type: "LoadIC",
				oldState: "polymorphic",
				newState: "megamorphic",
				key: "x",
				map: 61357696708641,
				optimizationState: "optimizable",
				severity: 3,
				modifier: "",
				slowReason: "",
			},
			{
				type: "LoadIC",
				oldState: "megamorphic",
				newState: "megamorphic",
				key: "x",
				map: 61357696709201,
				optimizationState: "optimized",
				severity: 3,
				modifier: "",
				slowReason: "",
			},
			{
				type: "LoadIC",
				oldState: "megamorphic",
				newState: "megamorphic",
				key: "x",
				map: 61357696707521,
				optimizationState: "optimized",
				severity: 3,
				modifier: "",
				slowReason: "",
			},
			{
				type: "LoadIC",
				oldState: "megamorphic",
				newState: "megamorphic",
				key: "x",
				map: 61357696703761,
				optimizationState: "optimized",
				severity: 3,
				modifier: "",
				slowReason: "",
			},
		],
	},

	"html-inline": {
		type: "ics",
		id: "19",
		functionName: "addAny",
		file: repoFileURL("examples/html-inline/adders.html"),
		line: 98,
		column: 33,
		severity: 3,
		updates: [
			{
				type: "LoadIC",
				oldState: "unintialized",
				newState: "monomorphic",
				key: "x",
				map: 22870837706697,
				optimizationState: "optimizable",
				severity: 1,
				modifier: "",
				slowReason: "",
			},
			{
				type: "LoadIC",
				oldState: "monomorphic",
				newState: "polymorphic",
				key: "x",
				map: 22870837706897,
				optimizationState: "optimizable",
				severity: 2,
				modifier: "",
				slowReason: "",
			},
			{
				type: "LoadIC",
				oldState: "polymorphic",
				newState: "polymorphic",
				key: "x",
				map: 22870837707137,
				optimizationState: "optimizable",
				severity: 2,
				modifier: "",
				slowReason: "",
			},
			{
				type: "LoadIC",
				oldState: "polymorphic",
				newState: "polymorphic",
				key: "x",
				map: 22870837707377,
				optimizationState: "optimizable",
				severity: 2,
				modifier: "",
				slowReason: "",
			},
			{
				type: "LoadIC",
				oldState: "polymorphic",
				newState: "megamorphic",
				key: "x",
				map: 22870837707617,
				optimizationState: "optimizable",
				severity: 3,
				modifier: "",
				slowReason: "",
			},
			{
				type: "LoadIC",
				oldState: "megamorphic",
				newState: "megamorphic",
				key: "x",
				map: 22870837707897,
				optimizationState: "optimized",
				severity: 3,
				modifier: "",
				slowReason: "",
			},
			{
				type: "LoadIC",
				oldState: "megamorphic",
				newState: "megamorphic",
				key: "x",
				map: 22870837708177,
				optimizationState: "optimized",
				severity: 3,
				modifier: "",
				slowReason: "",
			},
			{
				type: "LoadIC",
				oldState: "megamorphic",
				newState: "megamorphic",
				key: "x",
				map: 22870837708457,
				optimizationState: "optimized",
				severity: 3,
				modifier: "",
				slowReason: "",
			},
		],
	},

	"html-external": {
		type: "ics",
		id: "20",
		functionName: "addAny",
		file: repoFileURL("examples/html-external/adders.js"),
		line: 38,
		column: 27,
		severity: 3,
		updates: [
			{
				type: "LoadIC",
				oldState: "unintialized",
				newState: "monomorphic",
				key: "x",
				map: 72597969059665,
				optimizationState: "optimizable",
				severity: 1,
				modifier: "",
				slowReason: "",
			},
			{
				type: "LoadIC",
				oldState: "monomorphic",
				newState: "polymorphic",
				key: "x",
				map: 72597969059865,
				optimizationState: "optimizable",
				severity: 2,
				modifier: "",
				slowReason: "",
			},
			{
				type: "LoadIC",
				oldState: "polymorphic",
				newState: "polymorphic",
				key: "x",
				map: 72597969060105,
				optimizationState: "optimizable",
				severity: 2,
				modifier: "",
				slowReason: "",
			},
			{
				type: "LoadIC",
				oldState: "polymorphic",
				newState: "polymorphic",
				key: "x",
				map: 72597969060345,
				optimizationState: "optimizable",
				severity: 2,
				modifier: "",
				slowReason: "",
			},
			{
				type: "LoadIC",
				oldState: "polymorphic",
				newState: "megamorphic",
				key: "x",
				map: 72597969060585,
				optimizationState: "optimizable",
				severity: 3,
				modifier: "",
				slowReason: "",
			},
			{
				type: "LoadIC",
				oldState: "megamorphic",
				newState: "megamorphic",
				key: "x",
				map: 72597969060865,
				optimizationState: "optimized",
				severity: 3,
				modifier: "",
				slowReason: "",
			},
			{
				type: "LoadIC",
				oldState: "megamorphic",
				newState: "megamorphic",
				key: "x",
				map: 72597969061145,
				optimizationState: "optimized",
				severity: 3,
				modifier: "",
				slowReason: "",
			},
			{
				type: "LoadIC",
				oldState: "megamorphic",
				newState: "megamorphic",
				key: "x",
				map: 72597969061425,
				optimizationState: "optimized",
				severity: 3,
				modifier: "",
				slowReason: "",
			},
		],
	},
};
